### ISSUE TITLE
plugin path error

### ISSUE THREAD

**Issue by mrvbicakci** [SmartfaceIO/smfc-empty-workspace#2]
In the default project.json plugin path for Android is wrong.

It is same with iOS:
"plugins" : {
	"facebookios" : {
		"path" : "plugins/iOS/facebook.zip",
		"active" : false
	},
	"googleanalyticsplugin-ios" : {
		"path" : "plugins/iOS/GoogleAnalyticsiOS.zip",
		"active" : false
	}
}

**Comment by alperozisik** [comment]
Fixed
